name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  PORT: ${{ secrets.PORT }}
  FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Starting Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20.x.x
      - name: Install modules
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build project
        run: npm run build